#!/bin/bash
#
if [ "$#" -ne 2 ]; then
	echo "Usage: $0 <war-folder> <webapps-folder>"
	exit
fi

war_folder="$1"
webapps_folder="$2"

sudo service tomcat7 stop

sudo rm -r $webapps_folder/webapps/site/*
sudo rm -r $webapps_folder/webapps/site-staging/*
sudo rm -r $webapps_folder/webapps/cms/*
sudo rm -r $webapps_folder/webapps/ws/*
sudo rm -r /var/lib/tomcat7/work/Catalina/localhost/*

sudo unzip $war_folder/slepeweb-site-delivery.war -d $webapps_folder/webapps/site
sudo unzip $war_folder/slepeweb-site-delivery.war -d $webapps_folder/webapps/site-staging
sudo unzip $war_folder/slepeweb-cms.war -d $webapps_folder/webapps/cms
sudo unzip $war_folder/slepeweb-ws.war -d $webapps_folder/webapps/ws

sudo service apache2 stop
sudo rm -r /var/cache/apache2/mod_cache_disk/*
sudo service apache2 start

sudo service tomcat7 start
