<%@ 
    taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%><%@ 
    taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>

<h2>Web services</h2>

<p>This area for demonstrates a few RESTful and SOAP web services.</p>

<div id="tabs">
	<ul>
    <li><a href="#tabs-1">RESTful</a></li>
    <li><a href="#tabs-2">JAX-WS</a></li>
  </ul>

	<div id="tabs-1" class="compact">
		<article class="first">
			<h3>Lottery numbers service</h3>
			<p>
				The lottery numbers below are generated by a RESTful web service that
				is hosted on this server, using Spring MVC. An ajax request is made to retrieve the JSON
				representation of this resource. The web service URL is: 
				<a href="/ws/lotterynumbers/3">/ws/lotterynumbers/3</a>. If the 'Accept' header on the
				request is set to 'text/xml', then the service will return the data as XML.
			</p>
			<div id="lotterynumbers"></div>
			
			<br />
			<button type="button" class="button" id="lotteryrefresh">More numbers</button>
			<button type="button" class="button" id="lotteryclear">Clear</button>
		</article>
	</div>
	
	<div id="tabs-2" class="compact">
		<article class="first">
			<h3>Password generation service</h3>
			
			<p>
				This app takes a user-supplied seed value, and uses it to generate a password.
			</p>
			
			<table class="two-col-table">
				<tr>
					<td class="heading"><label for="org">Seed</label></td>
					<td><input id="password-org" type="text" name="org" size="16" /></td>
				</tr>
				<tr>
					<td class="heading"><label for="password">Password</label></td>
					<td><input id="password-pwd" type="text" name="password" size="16" readonly style="background: #cccccc" /></td>
				</tr>
			</table>
			
			<br />
			<button type="button" class="button" id="password-update">Get password</button>

			<p style="margin-top: 20px">
				This triggers an ajax request that calls a RESTful service, that in turn calls a 
				SOAP service. Both services are hosted on this server.
				The SOAP service digests the seed, generates a corresponding password, and returns that
				to the RESTful service, which returns a JSON object to the Ajax caller.
			</p>
			
			<p>(Inspect the <a href=/jaxws/password?wsdl>wsdl</a>)</p>
			
		</article>
	</div>

</div>
