<script>
	$.ajax({
		url : "/rest/lottery/numbers/3",
		dataType : "json",
		cache : false
	}).done(function(resp) {
		var html = "<table class='compact' width='450px' border='1'><tr>";
		for ( var i = 0; i < resp.lines.length; i++) {
			html += "<td width='33%'><u>" + resp.lines[i] + "</u></td>";
		}
		html += "</tr></table>";
		$("#lotterynumbers").append(html);
	}).fail(function(jqXHR, status) {
		//console.log(status);
	});
</script>

<article class="first">
	<h2>Sandbox</h2>
	<h3>Jersey, JAX-RS</h3>
	<p>
		The lottery numbers below are generated by a web service (REST) that
		is hosted on this server. The web service uses the Jersey
		implementation of JAX-RS. An ajax request is made to retrieve the JSON
		representation of this resource: <a href="/rest/lottery/numbers/3">Call
			service</a> for alternative XML representation ...
	</p>
	<div id="lotterynumbers"></div>
</article>
