
<div id="tabs">
	<ul>
    <li><a href="#tabs-1">JAX-RS</a></li>
    <li><a href="#tabs-2">JAX-WS</a></li>
  </ul>

	<div id="tabs-1" class="compact">
		<article class="first">
			<h3>Lottery numbers service</h3>
			<p>
				The lottery numbers below are generated by a web service (REST) that
				is hosted on this server. The web service uses the Jersey
				implementation of JAX-RS. An ajax request is made to retrieve the JSON
				representation of this resource: <a href="/rest/lottery/numbers/3">Call
					service</a> for alternative XML representation ...
			</p>
			<div id="lotterynumbers"></div>
			
			<br />
			<button type="button" class="button" id="lotteryrefresh">More numbers</button>
			<button type="button" class="button" id="lotteryclear">Clear</button>
		</article>
	</div>
	
	<div id="tabs-2" class="compact">
		<article class="first">
			<h3>Password generation service</h3>
			
			<p>
				Enter a seed string that identifies the company/website that the password is for,
				then click on the 'Get password' button.
			</p>
			
			<table class="two-col-table">
				<tr>
					<td class="heading"><label for="org">Seed</label></td>
					<td><input id="password-org" type="text" name="org" size="32" /></td>
				</tr>
				<tr>
					<td class="heading"><label for="password">Password</label></td>
					<td><input id="password-pwd" type="text" name="password" size="32" /></td>
				</tr>
			</table>
			
			<br />
			<button type="button" class="button" id="password-update">Get password</button>

			<p style="margin-top: 20px">
				This triggers an ajax request that calls a RESTful service, that in turn calls a 
				SOAP service. Both services are hosted on this server.
				The SOAP service digests the seed, generates a corresponding password, and returns that
				to the RESTful service, which returns a JSON object to the Ajax caller.
			</p>
			
			<p>(Inspect the <a href=/jaxws/password?wsdl>wsdl</a>)</p>
			
		</article>
	</div>
</div>